[package]
name = "mungos_rocket"
version = "0.0.1"
edition = "2021"
authors = ["MoghTech"]
description = "Helper macro for generating routes with Mungos"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
